apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: 629159009521.dkr.ecr.ap-south-1.amazonaws.com/helloword:VERSION
        ports:
        - name: nodeappport
          containerPort: 3001
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 0.5
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nodeappsvc
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
  - port: 80
    targetPort: nodeappport
    
